/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class enderwrapper_internal_Native */

#ifndef _Included_enderwrapper_internal_Native
#define _Included_enderwrapper_internal_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     enderwrapper_internal_Native
 * Method:    getClassBytecode
 * Signature: (Ljava/lang/Class;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_enderwrapper_internal_Native_getClassBytecode
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
